# Generated by Django 3.2.13 on 2022-05-01 14:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('aphorism', models.TextField(verbose_name='Aphorism')),
                ('aphorism_author', models.CharField(max_length=255, verbose_name='Aphorism author')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Star')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='about_us_team/', verbose_name='Image')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_team', to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Team',
                'verbose_name_plural': 'About Us Team',
                'db_table': 'about_us_team',
            },
        ),
        migrations.CreateModel(
            name='AboutUsStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_statistic', to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Statistic',
                'verbose_name_plural': 'About Us Statistic',
                'db_table': 'about_us_statistic',
            },
        ),
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(upload_to='about_us_info/', verbose_name='Icon')),
                ('mobile_icon', models.ImageField(upload_to='about_us_info/', verbose_name='Mobile icon')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_info', to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Info',
                'verbose_name_plural': 'About Us Info',
                'db_table': 'about_us_info',
            },
        ),
    ]
