# Generated by Django 4.0.4 on 2022-04-28 09:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('phone_prefix', models.IntegerField(choices=[('+994', '+994'), ('+7', '+7'), ('+1', '+1')], default='+994', verbose_name='Phone prefix')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.IntegerField(choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Internship')], default='full_time', verbose_name='Type')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Full Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('message', models.TextField(verbose_name='Message')),
                ('cv', models.FileField(upload_to='cv', verbose_name='CV')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicant',
            },
        ),
    ]
