# Generated by Django 4.0.4 on 2022-04-29 10:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('aphorism', models.TextField(verbose_name='Aphorism')),
                ('aphorism_author', models.CharField(max_length=255, verbose_name='Aphorism author')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='about_us_team', verbose_name='Image')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Team',
                'verbose_name_plural': 'About Us Team',
                'db_table': 'about_us_team',
            },
        ),
        migrations.CreateModel(
            name='AboutUsStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Statistic',
                'verbose_name_plural': 'About Us Statistic',
                'db_table': 'about_us_statistic',
            },
        ),
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(upload_to='about_us_info', verbose_name='Icon')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aboutus', verbose_name='About Us')),
            ],
            options={
                'verbose_name': 'About Us Info',
                'verbose_name_plural': 'About Us Info',
                'db_table': 'about_us_info',
            },
        ),
    ]
