# Generated by Django 4.0.4 on 2022-05-01 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='aphorism',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='aphorism_author',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan',
            field=models.TextField(default='', verbose_name='Slogan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_author',
            field=models.CharField(default='', max_length=255, verbose_name='Slogan author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_author_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Slogan author'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Slogan author'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Slogan author'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_az',
            field=models.TextField(null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_en',
            field=models.TextField(null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slogan_ru',
            field=models.TextField(null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusstatistic',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='full_name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='position_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='aboutusteam',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
    ]
