# Generated by Django 4.0.4 on 2022-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_aboutusteam_aboutusstatistic_aboutusinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusteam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
