# Generated by Django 4.0.4 on 2022-05-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aboutus_aphorism_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(verbose_name='Link')),
                ('icon', models.ImageField(upload_to='social_link/', verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='core.contactinfo', verbose_name='Contact info')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Link',
                'db_table': 'social_link',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phone', to='core.contactinfo', verbose_name='Contact info')),
            ],
            options={
                'verbose_name': 'Contact Phone',
                'verbose_name_plural': 'Contact Phone',
                'db_table': 'contact_phone',
            },
        ),
    ]
