# Generated by Django 4.0.4 on 2022-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo_sociallink_contactphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
