# Generated by Django 4.0.4 on 2022-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vacancy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.IntegerField(choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Internship')], default='full_time', verbose_name='Type'),
        ),
    ]
