# Generated by Django 4.0.4 on 2022-04-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_aboutusteam_is_active_aboutus_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusstatistic',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_statistic', to='core.aboutus', verbose_name='About Us'),
        ),
    ]
