# Generated by Django 4.0.4 on 2022-04-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aboutusstatistic_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfo',
            name='mobile_icon',
            field=models.ImageField(default='', upload_to='about_us_info', verbose_name='Mobile icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_info', to='core.aboutus', verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='aboutusteam',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_team', to='core.aboutus', verbose_name='About Us'),
        ),
    ]
