# Generated by Django 4.0.4 on 2022-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_prefix',
            field=models.IntegerField(choices=[('+994', '+994'), ('+7', '+7'), ('+1', '+1'), ('+90', '+90')], default='+994', verbose_name='Phone prefix'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship')], default='full_time', max_length=255, verbose_name='Type'),
        ),
    ]
