# Generated by Django 4.0.4 on 2022-05-02 11:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('phone_prefix', models.CharField(choices=[('+994', '+994'), ('+7', '+7'), ('+1', '+1'), ('+90', '+90')], max_length=200, verbose_name='Phone Prefix')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('activity_sphere', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, verbose_name='Activity Sphere')),
                ('website_url', models.URLField(verbose_name='Website URL')),
                ('new_domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Domain')),
                ('rival_website', models.TextField(blank=True, null=True, verbose_name='Rival Website')),
                ('liked_website', models.TextField(blank=True, null=True, verbose_name='Liked Website')),
                ('project_period', models.CharField(choices=[('2', '2 ay'), ('3', '3 ay'), ('6', '6 ay'), ('12', '12 ay')], max_length=200, verbose_name='Project Period')),
                ('design', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200, verbose_name='Design')),
                ('website_type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200, verbose_name='Website Type')),
                ('requirements', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200, verbose_name='Requirements')),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('az', 'az'), ('en', 'en'), ('ru', 'ru')], max_length=8, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
            },
        ),
        migrations.CreateModel(
            name='BriefPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_photo', to='website.brief', verbose_name='Brief')),
            ],
            options={
                'verbose_name': 'Brief Photo',
                'verbose_name_plural': 'Brief Photos',
            },
        ),
    ]
