# Generated by Django 4.0.4 on 2022-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='activity_sphere',
            field=models.CharField(choices=[('1', 'Activity 1'), ('2', 'Activity 2'), ('3', 'Activity 3'), ('4', 'Activity 4'), ('5', 'Activity 5')], max_length=200, verbose_name='Activity Sphere'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='design',
            field=models.CharField(choices=[('1', 'Design 1'), ('2', 'Design 2')], max_length=200, verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='requirements',
            field=models.CharField(choices=[('1', 'IOS'), ('2', 'Android'), ('3', 'Windows'), ('4', 'Mac'), ('5', 'Linux')], max_length=200, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='website_type',
            field=models.CharField(choices=[('1', 'E-commerce'), ('2', 'Blog'), ('3', 'Portal'), ('4', 'Sosial'), ('5', 'E-learning')], max_length=200, verbose_name='Website Type'),
        ),
    ]
