# Generated by Django 4.0.4 on 2022-04-27 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Body')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
