# Generated by Django 3.2.13 on 2022-05-01 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_az', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Body')),
                ('body_en', ckeditor.fields.RichTextField(null=True, verbose_name='Body')),
                ('body_az', ckeditor.fields.RichTextField(null=True, verbose_name='Body')),
                ('body_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Body')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('author_en', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('author_az', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blog',
            },
        ),
    ]
