# Generated by Django 4.0.4 on 2022-04-30 21:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
