# Generated by Django 3.2.13 on 2022-05-01 14:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='advantages/', verbose_name='Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Advantage',
                'verbose_name_plural': 'Service Advantages',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServicePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('price_per', models.CharField(max_length=200, verbose_name='Price per')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main')),
            ],
            options={
                'verbose_name': 'Service Packet',
                'verbose_name_plural': 'Service Packets',
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Specialist',
                'verbose_name_plural': 'Service Specialists',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(null=True)),
                ('full_description', ckeditor.fields.RichTextField(null=True)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('is_visible', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('advantages', models.ManyToManyField(blank=True, related_name='services_advantages', to='service.ServiceAdvantage')),
                ('categories', models.ManyToManyField(blank=True, related_name='services_categories', to='service.ServiceCategory')),
                ('packets', models.ManyToManyField(blank=True, related_name='services_packets', to='service.ServicePacket')),
                ('projects', models.ManyToManyField(blank=True, related_name='services_projects', to='portfolio.ServiceProject')),
                ('specialists', models.ManyToManyField(blank=True, related_name='services_specialists', to='service.ServiceSpecialist')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('phone_prefix', models.CharField(max_length=255, verbose_name='Phone prefix')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('cv', models.FileField(blank=True, null=True, upload_to='applicants/')),
                ('application_id', models.PositiveIntegerField()),
                ('site_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Site link')),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link')),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram link')),
                ('application_type', models.ForeignKey(limit_choices_to={'model__in': ['service', 'serviceproject', 'vacancy']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Application type')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicant',
            },
        ),
    ]
