# Generated by Django 4.0.4 on 2022-04-28 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('period', models.CharField(max_length=200, verbose_name='Period')),
                ('icon', models.ImageField(upload_to='process/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Project Process',
                'verbose_name_plural': 'Project Processes',
            },
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project Result',
                'verbose_name_plural': 'Project Results',
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='advantages/', verbose_name='Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Advantage',
                'verbose_name_plural': 'Service Advantages',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServicePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('price_per', models.CharField(max_length=200, verbose_name='Price per')),
            ],
            options={
                'verbose_name': 'Service Packet',
                'verbose_name_plural': 'Service Packets',
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Specialist',
                'verbose_name_plural': 'Service Specialists',
            },
        ),
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('images', models.ManyToManyField(related_name='project_images', to='service.projectimage', verbose_name='Images')),
                ('process', models.ManyToManyField(related_name='project_process', to='service.projectprocess', verbose_name='Process')),
                ('results', models.ManyToManyField(related_name='project_results', to='service.projectresult', verbose_name='Results')),
            ],
            options={
                'verbose_name': 'Service Project',
                'verbose_name_plural': 'Service Projects',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(null=True)),
                ('full_description', ckeditor.fields.RichTextField(null=True)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('advantages', models.ManyToManyField(blank=True, related_name='services_advantages', to='service.serviceadvantage')),
                ('categories', models.ManyToManyField(blank=True, related_name='services_categories', to='service.servicecategory')),
                ('packets', models.ManyToManyField(blank=True, related_name='services_packets', to='service.servicepacket')),
                ('projects', models.ManyToManyField(blank=True, related_name='services_projects', to='service.serviceproject')),
                ('specialists', models.ManyToManyField(blank=True, related_name='services_specialists', to='service.servicespecialist')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('title',),
            },
        ),
    ]
