# Generated by Django 4.0.4 on 2022-04-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_project_slug_alter_service_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
