# Generated by Django 4.0.4 on 2022-04-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicepacket_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicepacket', verbose_name='Packet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Packet Applicant',
                'verbose_name_plural': 'Packet Applicants',
                'db_table': 'packet_applicant',
            },
        ),
    ]
