# Generated by Django 3.2.13 on 2022-05-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0002_applicant_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='application_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['service', 'serviceproject', 'vacancy']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Application type'),
        ),
    ]
