# Generated by Django 4.0.4 on 2022-04-29 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_packetapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Statistic',
                'verbose_name_plural': 'Service Statistics',
            },
        ),
        migrations.RemoveField(
            model_name='serviceproject',
            name='image',
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='cover_image',
            field=models.ImageField(default='', upload_to='projects/', verbose_name='Cover Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='statistics',
            field=models.ManyToManyField(related_name='project_statistics', to='service.servicestatistic', verbose_name='Statistics'),
        ),
    ]
