# Generated by Django 3.2.13 on 2022-05-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('service', '0003_auto_20220501_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='application_type',
        ),
        migrations.AddField(
            model_name='applicant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.serviceproject', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='vacancy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='career.vacancy', verbose_name='Vacancy'),
            preserve_default=False,
        ),
    ]
