# Generated by Django 4.0.4 on 2022-04-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicestatistic_remove_serviceproject_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceStatistic',
            new_name='ProjectStatistic',
        ),
    ]
