# Generated by Django 3.2.13 on 2022-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220501_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='service',
        ),
    ]
