# Generated by Django 4.0.4 on 2022-04-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_servicestatistic_projectstatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatistic',
            options={'verbose_name': 'Project Statistic', 'verbose_name_plural': 'Project Statistics'},
        ),
        migrations.CreateModel(
            name='ServiceApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('phone_prefix', models.CharField(max_length=255, verbose_name='Phone prefix')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Applicant',
                'verbose_name_plural': 'Service Applicants',
                'db_table': 'service_applicant',
            },
        ),
    ]
