# Generated by Django 3.2.13 on 2022-05-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_applicant_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Service'),
        ),
    ]
