# Generated by Django 4.0.4 on 2022-04-30 17:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_projectstatistic_options_serviceapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAuditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Digital Audit Info',
                'verbose_name_plural': 'Digital Audit Info',
            },
        ),
        migrations.CreateModel(
            name='DigitalAuditAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('digital_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.digitalauditinfo', verbose_name='Digital Audit')),
            ],
            options={
                'verbose_name': 'Digital Audit Accordion',
                'verbose_name_plural': 'Digital Audit Accordion',
            },
        ),
    ]
