# Generated by Django 3.2.13 on 2022-05-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_applicant_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='vacancy',
        ),
    ]
