# Generated by Django 4.0.4 on 2022-04-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_digitalauditinfo_digitalauditaccordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalauditaccordion',
            name='digital_audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_audit_accordions', to='service.digitalauditinfo', verbose_name='Digital Audit'),
        ),
    ]
