# Generated by Django 4.0.4 on 2022-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_digitalauditaccordion_digital_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAuditApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone_prefix', models.CharField(max_length=255, verbose_name='Phone prefix')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('site_link', models.URLField(max_length=255, verbose_name='Site link')),
                ('facebook_link', models.CharField(max_length=255, verbose_name='Facebook link')),
                ('instagram_link', models.CharField(max_length=255, verbose_name='Instagram link')),
            ],
            options={
                'verbose_name': 'Digital Audit Applicant',
                'verbose_name_plural': 'Digital Audit Applicants',
                'db_table': 'digital_audit_applicant',
            },
        ),
    ]
