# Generated by Django 3.2.13 on 2022-05-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('career', '0001_initial'),
        ('service', '0008_auto_20220501_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.serviceproject', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.vacancy', verbose_name='Vacancy'),
        ),
    ]
