# Generated by Django 3.2.13 on 2022-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20220501_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name'),
        ),
    ]
