# Generated by Django 4.0.4 on 2022-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_digitalauditapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalauditapplicant',
            name='phone_prefix',
            field=models.IntegerField(choices=[('+994', '+994'), ('+7', '+7'), ('+1', '+1'), ('+90', '+90')], verbose_name='Phone prefix'),
        ),
    ]
