# Generated by Django 4.0.4 on 2022-05-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_digitalauditapplicant_phone_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
