# Generated by Django 3.2.13 on 2022-05-01 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('period', models.CharField(max_length=200, verbose_name='Period')),
                ('icon', models.ImageField(upload_to='process/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Project Process',
                'verbose_name_plural': 'Project Processes',
            },
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project Result',
                'verbose_name_plural': 'Project Results',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project Statistic',
                'verbose_name_plural': 'Project Statistics',
            },
        ),
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='projects/', verbose_name='Cover Image')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('images', models.ManyToManyField(related_name='project_images', to='portfolio.ProjectImage', verbose_name='Images')),
                ('process', models.ManyToManyField(related_name='project_process', to='portfolio.ProjectProcess', verbose_name='Process')),
                ('results', models.ManyToManyField(related_name='project_results', to='portfolio.ProjectResult', verbose_name='Results')),
                ('statistics', models.ManyToManyField(related_name='project_statistics', to='portfolio.ProjectStatistic', verbose_name='Statistics')),
            ],
            options={
                'verbose_name': 'Service Project',
                'verbose_name_plural': 'Service Projects',
                'db_table': 'service_project',
            },
        ),
    ]
