# Generated by Django 4.0.4 on 2022-05-01 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocess',
            name='period_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='projectprocess',
            name='period_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='projectprocess',
            name='period_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='projectprocess',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectprocess',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectprocess',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='name_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='serviceproject',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='project_images', to='portfolio.projectimage', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='serviceproject',
            name='process',
            field=models.ManyToManyField(blank=True, related_name='project_process', to='portfolio.projectprocess', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='serviceproject',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='project_results', to='portfolio.projectresult', verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='serviceproject',
            name='statistics',
            field=models.ManyToManyField(blank=True, related_name='project_statistics', to='portfolio.projectstatistic', verbose_name='Statistics'),
        ),
    ]
