# Generated by Django 4.0.4 on 2022-05-10 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectprocess_period_az_projectprocess_period_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproject',
            name='aims',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Aims'),
            preserve_default=False,
        ),
    ]
