# Generated by Django 4.0.4 on 2022-05-10 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_serviceproject_aims'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproject',
            name='aims_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Aims'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='aims_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Aims'),
        ),
        migrations.AddField(
            model_name='serviceproject',
            name='aims_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Aims'),
        ),
    ]
